context:
  version: 5.3.1

package:
  name: gtsjs
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/gts/-/gts-${{ version }}.tgz
  sha256: b6d34b766e8b2aa8b7d19567871d349fe0680c41b8897ecba76c768dc79db9b1

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - gts --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: TypeScript style guide, formatter, and linter.
  homepage: https://github.com/google/gts
  repository: https://github.com/google/gts

extra:
  recipe-maintainers:
    - danielnachun
